default_job = "check"

[jobs.check]
command = ["cargo", "check", "--workspace", "--color", "always"]
watch = ["resource"]

[jobs.clippy]
command = ["cargo", "clippy", "--workspace", "--all-targets", "--color", "always", "--", "-D", "warnings"]
watch = ["resource"]

[jobs.test]
command = ["cargo", "test", "--workspace", "--color", "always"]
watch = ["resource"]

[jobs.fmt]
command = ["cargo", "fmt", "--all"]
watch = ["resource"]

[keybindings]
c = "job:clippy"
t = "job:test"
f = "job:fmt"
