sonar.projectKey=cntm-labs_strata
sonar.projectName=strata
sonar.sources=.
sonar.host.url=http://sonarqube.devops.svc.cluster.local:9000
sonar.exclusions=**/*.java, **/node_modules/**, **/dist/**, **/build/**, **/.git/**
