INSERT INTO dashboard_templates (slug, name, description, category, dashboard_json, required_datasource_type) VALUES
('node-exporter', 'Node Exporter', 'System metrics: CPU, memory, disk, network', 'infrastructure',
 '{"panels":[{"title":"CPU Usage","type":"timeseries","query":"100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)","position":{"x":0,"y":0,"w":6,"h":3}},{"title":"Memory Usage","type":"gauge","query":"(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100","position":{"x":6,"y":0,"w":3,"h":3}},{"title":"Disk Usage","type":"gauge","query":"(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100","position":{"x":9,"y":0,"w":3,"h":3}}]}',
 'prometheus'),
('chorus-overview', 'Chorus Overview', 'CPaaS metrics: messages sent, delivery rates, latency', 'cpaas',
 '{"panels":[{"title":"Messages Sent","type":"stat","query":"sum(chorus_messages_total)","position":{"x":0,"y":0,"w":3,"h":2}},{"title":"Delivery Rate","type":"gauge","query":"sum(rate(chorus_delivered_total[5m])) / sum(rate(chorus_messages_total[5m])) * 100","position":{"x":3,"y":0,"w":3,"h":2}},{"title":"Message Volume","type":"timeseries","query":"sum(rate(chorus_messages_total[5m])) by (channel)","position":{"x":0,"y":2,"w":12,"h":3}}]}',
 'prometheus'),
('nucleus-auth', 'Nucleus Auth', 'Auth metrics: login rate, active sessions, errors', 'auth',
 '{"panels":[{"title":"Active Sessions","type":"stat","query":"nucleus_active_sessions","position":{"x":0,"y":0,"w":3,"h":2}},{"title":"Login Rate","type":"timeseries","query":"rate(nucleus_login_total[5m])","position":{"x":3,"y":0,"w":9,"h":3}}]}',
 'prometheus'),
('postgresql', 'PostgreSQL', 'Database metrics: connections, query time, cache hit ratio', 'database',
 '{"panels":[{"title":"Active Connections","type":"stat","query":"pg_stat_activity_count","position":{"x":0,"y":0,"w":3,"h":2}},{"title":"Cache Hit Ratio","type":"gauge","query":"pg_stat_database_blks_hit / (pg_stat_database_blks_hit + pg_stat_database_blks_read) * 100","position":{"x":3,"y":0,"w":3,"h":2}},{"title":"Query Duration","type":"timeseries","query":"rate(pg_stat_statements_total_time[5m])","position":{"x":0,"y":2,"w":12,"h":3}}]}',
 'prometheus'),
('redis', 'Redis', 'Redis metrics: memory, ops/sec, hit rate', 'database',
 '{"panels":[{"title":"Memory Used","type":"stat","query":"redis_memory_used_bytes","position":{"x":0,"y":0,"w":3,"h":2}},{"title":"Ops/sec","type":"timeseries","query":"rate(redis_commands_processed_total[5m])","position":{"x":3,"y":0,"w":9,"h":3}}]}',
 'prometheus'),
('blank', 'Custom Blank', 'Start from scratch', 'custom',
 '{"panels":[]}',
 NULL);
